### ISSUE TITLE
installation fails with "Skipping 1 packages not available: bamUtils"

### ISSUE THREAD

**Issue by funnell** [mskilab/JaBbA#24]
Probably just missing bamUtils in your remotes

**Comment by mjko1210** [comment]
Hi, is there any update on this?
I couldn't install the package with same issues.

> ** byte-compile and prepare package for lazy loading
> Error: package or namespace load failed for ‘bamUtils’:
 (converted from warning) replacing previous import ‘GenomicRanges::shift’ by ‘data.table::shift’ when loading ‘bamUtils’
Error: package ‘bamUtils’ could not be loaded
Execution halted
ERROR: lazy loading failed for package ‘Ppurple’.`

**Comment by imielinski** [comment]
Sorry for the late reply – we should update the install instructions.

You have to set this environment variable otherwise install_github errors out on any warning during package install (also for dependencies).

## allows dependencies that throw warnings to install
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = TRUE)

May be good to put this in your .Rprofile or set the env variable in your .bash_profile

Marcin

**Comment by xtYao** [comment]
We removed bamUtils from the dependency chain. This is related to the Ppurple package which we also suspended in JaBbA until we reduce its dependency lists.
