### ISSUE TITLE
definition of coverage

### ISSUE THREAD

**Issue by mjko1210** [mskilab/JaBbA#27]
Hi,

Could you give me more details on what's the definition of coverage as JaBba input ?
I have coverage for both tumor and normal. However, when I checked example coverage.txt (from extdata/coverage.txt) , it has column "ratio". I wasn't familiar how this coverage was calculated. 

I assume coverage, segments and junctions are all based on tumor. (except HET-- this requires both tumor and normal to calculate alt.count & ref.count

Thanks!

**Comment by mskilab** [comment]
Sure, the coverage just has to be binned read depth - it can be raw counts,
GC corrected,or  tumor / normal ratio.

The only real requirement is that the read depth in the bin is *proportional
*to the amount of locus in that bin in the tumor sample +/- noise.

Any distortion from that may give you false positive loose ends and/or
incorrect copy number - eg GC waves, or incorrect CN on X Y

In the example, we use tumor / normal ratio.  Dividing by the normal is one
way to straighten out the tumor read depth - but often can actually
introduce noise and distortions.  A better option is to use our dryclean
tool.  However, we leave the upstream read depth normalization up to the
user.

But note that the simple tumor / normal ratio "as is" violates the above
requirement for X Y since the ratio will be 1.   So if you use the tumor /
normal ratio to normalize your read depth our advice is to divide every
normal bin by it's chromosomal median ie tumor(i) *
normal_median(chromosome(i))  / normal(i)

That should keep XY proportional for both males and females

**Comment by xtYao** [comment]
Please see the second item in the FAQ.
